### PR TITLE
reduced log chattiness - changed level of log0 messages

### PR DESCRIPTION
**Pull request by dannyzaken**
Signed-off-by: Danny Zaken <dannyzaken@gmail.com>

### Explain the changes
1. fixed several error\warn messages that were printed with `dbg.log0` level
2. part of an effort to support reduced log chattiness by reducing log level to warn\err only
3. for some repeating messages increased the log level to `log1`

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1. 

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
LGTM,
In General this is a good practice, even when the logs are only printed in a catch of an error, printing them in `dbg0` will cause it to be ignored in the case where we set the debug level to `warn` in the config map
https://github.com/noobaa/noobaa-core/blob/069e2f6c58e0a205a876fa8d0f84d68d3971e286/src/util/debug_config.js#L27-L31

**Comment by romayalon** [comment]
@dannyzaken @liranmauda 
There are several log messages that I specifically was asked to keep as log0 and not an error/warning.
maybe we should decide on well-defined rules for it.

**Comment by dannyzaken** [comment]
> @dannyzaken @liranmauda There are several log messages that I specifically was asked to keep as log0 and not an error/warning. maybe we should decide on well-defined rules for it.

@romayalon what is the reason to keep it in log0?

**Comment by romayalon** [comment]
@guymguym can you please share your logging methodology?

**Review by liranmauda — APPROVED** [review]

**Pull request merged**
