### PR TITLE
Disable NSFS md5 calculation

### PR DESCRIPTION
**Pull request by romayalon**
Signed-off-by: Romy <romy2232@gmail.com>

### Explain the changes
1. 

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

### CODE REVIEW

**Comment by guymguym** [comment]
@romayalon Can you provide more info of why change the default to false?

**Comment by nimrod-becker** [comment]
@guymguym This was requested for the initial release of NS FS

**Comment by guymguym** [comment]
OK, I guess this is a temporary solution anyway.
Going forward this would have to go to the nsfs_account_config or nsfs_bucket_config because it can't really be a system wide configuration, and then we will only have to decide the default for new accounts/buckets.

**Comment by nimrod-becker** [comment]
totally agree

**Review by nimrod-becker — APPROVED** [review]

**Pull request merged**
