### PR TITLE
get cm256 using git subtree

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
1. Remove the cm256 directory - preparing to fetch it using `git subtree`
2. Run `git subtree add --squash -P src/native/third_party/cm256 git://github.com/catid/cm256.git master` in order to get the cm256 directory
3. Cleaned the cm256 directory to match the one we had previously 
4. Manually added @yselkowitz changes from https://github.com/catid/gf256/pull/6

### CODE REVIEW

**Comment by liranmauda** [comment]
Hi @yselkowitz 
Can you have a look?

**Comment by guymguym** [comment]
@liranmauda Please notice we added a DCO check - you need to sign off your commits with  `git commit --signoff --amend` or `git rebase --signoff master` to mass signoff all commits rebased on top of master.

**Comment by liranmauda** [comment]
I saw that 🙂 
`git rebase HEAD~5 --signoff` giving me hard time...

**Comment by yselkowitz** [comment]
The P&Z specific commit (which is the only net change) is correct, I can't comment as to the git subtree infrastructure side of it.

**Comment by liranmauda** [comment]
Closing this PR as it turns out that handling with `git subtree` is hard when rebasing.
Eventually it creates a commit (the squash commit) that have those values:
```
git-subtree-dir: src/native/third_party/cm256
git-subtree-split: caa2022c140a6f5ff32b8b2b5ac3b7131da99ca9
```
and a merge commit.

We should probably use `git submodules` instead.
It creates a repo inside of our repo. 
That repo contained a .gitmodules file in the root directory which have:
```
submodule "native_modules/cm256"]
	path = native_modules/cm256
	url = https://github.com/noobaa/cm256
```
and `git submodule status` will look like this:
```
caa2022c140a6f5ff32b8b2b5ac3b7131da99ca9 native_modules/cm256
```
which contains the commit hash.

**Pull request closed without merging**
