### PR TITLE
arch != x64: rebase cm256, no -msse4.1, no isa-l/erasure_code

### PR DESCRIPTION
**Pull request by guymguym**
CC @liranmauda @yselkowitz @SaravanaStorageNetwork

### Explain the changes
1. Update g256 code from upstream cm256
2. Added condition to only use -msse4.1 when arch=x64
3. Skip isa-l/erasure_code compile on non x64

### Issues: Fixed #xxx / Gap #xxx
1. None

### Testing Instructions:
1. Build linux x64
2. Build s390x

### CODE REVIEW

**Comment by yselkowitz** [comment]
This isn't enough for Power or Z, a few additional changes are needed.   I would like to suggest breaking this up:

1. Conditionalize -msse4.1
2. Rebase cm256
3. Add additional code for P&Z

**Comment by guymguym** [comment]
@yselkowitz So 1 & 2 are handled here. Just item 3 is missing?

**Comment by guymguym** [comment]
Added a condition to skip isa-l/erasure_code compile on non x64.
Refer to this stale issue for actual isa-l support for PPC - https://github.com/intel/isa-l/issues/7

**Review by liranmauda — APPROVED** [review]

**Review by nimrod-becker — APPROVED** [review]

**Comment by mykaul** [comment]
Shouldn't we compile with AVX2?

**Comment by guymguym** [comment]
@mykaul ISA-L doesn't support s390x arch yet. See the linked issue above.

**Comment by mykaul** [comment]
I thought about compiling with AVX2 for X64. Did we remove the per-platform optimizations altogether now?

**Comment by guymguym** [comment]
@mykaul Ok so this PR is only for **non** x86_64.
On x64, ISA-L is compiled with all optimizations and it can check for supported cpu features on runtime (sse, avx, avx2, avx512). 

Specifically for s390x there is no optimized Instructions support in ISA-L, and for powerpc the support is there but we haven’t tried that yet.

Is that clearer?

**Comment by mykaul** [comment]
Sure, thanks.

**Pull request merged**
