### PR TITLE
Fix isa-l_crypto for multi-arch

### LINKED ISSUE #5894: Cannot build nooba core in power (ppc64le) architecture
### Environment info
- NooBaa Version: **5.3.0**
- Architecture: **ppc64le**

### Actual behavior
1. My goal is to build nooba core for power. I first did the necessary changes on the dockerfiles to use the corresponding binary files and docker images. Currently it fails when running `npm run build:native`. I think it has to do with the sse2 flags on the GF256 library. In this repo https://github.com/YiannisGkoufas/noobaa-core is the ongoing effort to build nooba core for power. I used some wrappers from LLVM but I am stuck.

### Expected behavior
1. To successfully build nooba core

### Steps to reproduce
1. Clone the repo in a power machine
2. Build it from source

### More information - Screenshots / Logs / Other output

[errors.txt](https://github.com/noobaa/noobaa-core/files/4148487/errors.txt)

### PR DESCRIPTION
**Pull request by yselkowitz**
### Explain the changes
These commits, in addition to those pending elsewhere, should fix the build on ppc64le/s390x.

### Testing Instructions:
1. Import https://github.com/catid/gf256/pull/6 into src/native/third_party/cm256
2. Build on x86_64 and ppc64le and/or s390x

### CODE REVIEW

**Comment by guymguym** [comment]
Hi @yselkowitz 
Are these changes already upstream in isa-l_crypto?

**Comment by yselkowitz** [comment]
The first two are, yes.  Upstream doesn't have .gyp files, so that's noobaa-specific anyway.

**Comment by guymguym** [comment]
@yselkowitz Is this a rebase to one of the cm256 / isa-l releases? or are we cherry picking?

@liranmauda This is related to the rational for using git submodules to manage this dependency properly with a tool like git instead of doing those manual code syncronizations.

**Comment by guymguym** [comment]
See https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407

**Comment by guymguym** [comment]
But based on this - https://martowen.com/2016/05/01/git-submodules-vs-git-subtrees/
git subtree is easier to pull and harder to push, which seems more suitable,
and that would keep the entire sources in our repo as well.

**Comment by guymguym** [comment]
Anyway, for the scope of this PR my questions are:
1. Are we doing full rebase or have to cherry pick?
2. Can we try using git subtree? (maybe --squash is a good option too)

**Comment by b-ranto** [comment]
Thanks Yaakov! I can confirm I got a successful (d/s) build with the patches in this PR and in https://github.com/catid/gf256/pull/6

**Review by b-ranto — APPROVED** [review]
Helped me build the noobaa-core on s390x and ppc64le downstream.

**Comment by liranmauda** [comment]
> Anyway, for the scope of this PR my questions are:
> 
> 1. Are we doing full rebase or have to cherry-pick?
> 2. Can we try using git subtree? (maybe --squash is a good option too)

Hi @yselkowitz 
How did we fetch the code from it's upstream?
Was it a Cherry-pick? from which commit did we get it?

Can We use `git subtree`? supposedly it will point to the upstream commit.

We want to merge this code and do https://github.com/catid/gf256/pull/6 as a patch for now.

**Comment by yselkowitz** [comment]
These were manual imports from the latest upstream code as of the time I made them.  The base implementations have been in the code for a long time, but they weren't copied in here when the rest of the code was.  The header fix mentions the upstream commit in its commit message.

**Review by liranmauda — APPROVED** [review]
LGTM

**Comment by liranmauda** [comment]
@yselkowitz can you rebase? 
Then we can merge. Thanks

**Pull request merged**
