### PR TITLE
Add cloud identity to pool cloud info

### PR DESCRIPTION
**Pull request by kfir-payne**
Signed-off-by: Kfir Payne <kfirpayne@gmail.com>

related https://github.com/noobaa/noobaa-core/issues/5750

### Explain the changes
1.  Add `identity` field in the `info.cloud_info` returned object from `read_system()`.
2. Add the same field in the appropriate json schema.

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1. Verify the Resources tab in the UI shows the resources properly.
2. Verify a specific cloud Resource tab in the UI shows the resource info properly.

### CODE REVIEW

**Comment by nimrod-becker** [comment]
verify the UI doesn't break on the resources screen and a single resource screen

**Comment by kfir-payne** [comment]
@nimrod-becker The UI doesn't seems to break, should I add it as a test instruction?

**Comment by nimrod-becker** [comment]
Sure

**Review by dannyzaken — APPROVED** [review]
@kfir-payne LGTM
just make sure before merging that this causes the operator to stop printing the connection mismatch warning and that it behaves correctly after the change

**Comment by liranmauda** [comment]
@dannyzaken @kfir-payne 
Please pay attention to the `package-lock.json` next time.
Do not commit and marge it.

**Comment by dannyzaken** [comment]
@liranmauda sorry, my bad

**Pull request merged**
