### PR TITLE
Pre-build lib files and include it in the repository

### PR DESCRIPTION
**Pull request by nb-ohad**
### Explain the changes
Refactor the lib build process into an offline task. Upon lib dependencies change the developer should run this task on his dev environment and include the results (the src/lib folder) in the commit that is pushed to the repository.

This removes any dependencies on bower in our upstream and downstream automated build processes. automated build processes.

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

### CODE REVIEW

**Review by liranmauda — APPROVED** [review]
One comment:
Instead of running `npm run build-deps` we can add an entry to the Makefile

**Comment by nb-ohad** [comment]
@liranmauda I am not sure a make file entry is needed as this command should run only when the dependencies change and on the dev computer itself and the result should be pushed into the repo

**Review by nimrod-becker — APPROVED** [review]

**Comment by nimrod-becker** [comment]
@guymguym just FYI

**Comment by nb-ohad** [comment]
We can always add a make target in a future commit if we find that it is necessary

**Pull request merged**
