### PR TITLE
Bumping isa-l to v2.31.0

### LINKED ISSUE #7945: deps: update to latest isa-l v2.31 to allow building on mac arm64
### Environment info
- NooBaa Version: **5.16**
- Platform: **MacOS arm64**

### Actual behavior
1. Using node for arm64 the build fails on:
```
$ node -v
v20.11.0

$ node -p process.arch
arm64

$ npm run clean
...

$ npm install
...

$ npm run build

> noobaa-core@5.16.0 build
> npm run build:native


> noobaa-core@5.16.0 build:native
> node-gyp configure && node-gyp build

gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.11.0 | darwin | arm64
gyp info find Python using Python version 3.12.2 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"

gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
gyp info spawn args [
gyp info spawn args './node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args './build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args './node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '~/Library/Caches/node-gyp/20.11.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=~/Library/Caches/node-gyp/20.11.0',
gyp info spawn args '-Dnode_gyp_dir=./node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=~/Library/Caches/node-gyp/20.11.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=.b',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@20.11.0 | darwin | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CXX(target) Release/obj.target/cm256/src/native/third_party/cm256/cm256.o
  CXX(target) Release/obj.target/cm256/src/native/third_party/cm256/gf256.o
  LIBTOOL-STATIC Release/cm256.a
  CXX(target) Release/obj.target/snappy/src/native/third_party/snappy/snappy-c.o
  CXX(target) Release/obj.target/snappy/src/native/third_party/snappy/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/src/native/third_party/snappy/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/src/native/third_party/snappy/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CC(target) Release/obj.target/isa-l-ec/src/native/third_party/isa-l/erasure_code/ec_base.o
  CC(target) Release/obj.target/isa-l-ec/src/native/third_party/isa-l/erasure_code/aarch64/ec_aarch64_highlevel_func.o
  CC(target) Release/obj.target/isa-l-ec/src/native/third_party/isa-l/erasure_code/aarch64/ec_aarch64_dispatcher.o
In file included from ../src/native/third_party/isa-l/erasure_code/aarch64/ec_aarch64_dispatcher.c:29:
../src/native/third_party/isa-l/include/aarch64_multibinary.h:34:10: fatal error: 'asm/hwcap.h' file not found
#include <asm/hwcap.h>
         ^~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/isa-l-ec/src/native/third_party/isa-l/erasure_code/aarch64/ec_aarch64_dispatcher.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (./node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.4.0
gyp ERR! command "~/.nvm/versions/node/v20.11.0/bin/node" "./node_modules/.bin/node-gyp" "build"
gyp ERR! cwd .
gyp ERR! node -v v20.11.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok

```

2. Seems like upgrading isa-l to v2.31 includes a fix:
https://github.com/intel/isa-l/commit/ad39d7ccfdf1d494d821d234db9af194364d2ae0
https://github.com/intel/isa-l/releases/tag/v2.31.0

### Expected behavior
1. Should be able to build on Mac arm64 

### Steps to reproduce
1. See above.

### PR DESCRIPTION
**Pull request by liranmauda**
### Explain the changes
Bumping isa-l to v2.31.0

### Issues: Fixed #xxx / Gap #xxx
1. Fixes: #7945

### CODE REVIEW

**Review by guymguym — CHANGES_REQUESTED** [review]
should update [versions.md](https://github.com/noobaa/noobaa-core/blob/master/src/native/third_party/versions.md)

**Comment by liranmauda** [comment]
> @liranmauda does this build successfully on mac arm64 now?

I have managed to build it on my mac (M1)

**Comment by guymguym** [comment]
@liranmauda It fails on mac with node for arm64. 

We need to add a condition to the [mac section to handle node_arch=x64 vs arm64 like we do for linux](https://github.com/noobaa/noobaa-core/blob/dbe81f9545fdc2321b755fdcaa8d45e11aba9496/src/native/asm.gypi#L55). 

In the isa-l readme and makefile it shows that on arm the toolchain to use is gcc/gas.
However when I tried it I had some issues on my mac so it might need more configuration to work out.

If you want we can merge this anyway to start running regression with the updated code, and fix the mac arm build in next PR.

**Comment by liranmauda** [comment]
> @liranmauda It fails on mac with node for arm64.
> 
> We need to add a condition to the [mac section to handle node_arch=x64 vs arm64 like we do for linux](https://github.com/noobaa/noobaa-core/blob/dbe81f9545fdc2321b755fdcaa8d45e11aba9496/src/native/asm.gypi#L55).
> 
> In the isa-l readme and makefile it shows that on arm the toolchain to use is gcc/gas. However when I tried it I had some issues on my mac so it might need more configuration to work out.
> 
> If you want we can merge this anyway to start running regression with the updated code, and fix the mac arm build in next PR.


@guymguym I agree, probably we need to do the same as in the Linux.
We can merge this so the code will be there and run.

I will rebase, and when it is approved I will merge it.

**Review by guymguym — APPROVED** [review]

**Pull request merged**
