### PR TITLE
Post Node v16 dependency bumps

### PR DESCRIPTION
**Pull request by tangledbytes**
### Explain the changes
Following dependencies were bumped

```
====================================================
####### MINOR/PATCH DEPENDENCY UPGRADES ###########
====================================================
@google-cloud/storage     6.5.0  →     6.5.2 DONE
@types/lodash          4.14.185  →  4.14.186 DONE
@types/node            16.11.59  →  16.11.63 DONE
aws-sdk                2.1217.0  →  2.1227.0 DONE
eslint                   8.23.1  →    8.24.0 DONE
typescript                4.8.3  →     4.8.4 DONE
ws                        8.8.1  →     8.9.0 DONE
yaml                      2.1.1  →     2.1.2 DONE
====================================================
```

eslint version 8.24.0 enforced a new rule `logical-assignment-operators` The relevant changes were made to all the files. It should be noted that `||=` operator is available in es2021 and hence the language allowed by eslint was also changed.

### Testing Instructions:
1. `make test`
2. `make test-postgres`

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Review by liranmauda — COMMENTED** [review]
LGTM, @guymguym What do you think?

**Comment by guymguym** [comment]
@liranmauda I just think that the `||=` global change is a bit risky, and not strictly required.

**Comment by liranmauda** [comment]
> @liranmauda I just think that the `||=` global change is a bit risky, and not strictly required.

@utkarsh-pro Based on @guymguym comment, I guess we can drop this PR.

**Comment by utkarsh-pro** [comment]
Yep, closing.

**Pull request closed without merging**
