### PR TITLE
typos

### LINKED ISSUE #6594: typo nubmer on several frontend and components locations
### Environment info
- NooBaa Version: all
- Platform: NA

### Actual behavior
1.Nubmer typo found in several frontent files. Example: Nubmer of pods, Nubmer of nodes, buildNubmer, etc. 

### Expected behavior
1.Should be replaced with Number.

### Steps to reproduce
1.NA

### More information - Screenshots / Logs / Other output
Screenshot 2021-06-22 at 10 59 17

### PR DESCRIPTION
**Pull request by rflorenc**
### Explain the changes
1. Fixed small typos.

### Issues: Fixed #xxx / Gap #xxx
1. Fix #6594 

### Testing Instructions:
1. NA

### CODE REVIEW

**Review by nimrod-becker — APPROVED** [review]

**Comment by liranmauda** [comment]
Hi @rflorenc 
Thanks for the PR! 

We need to do several things for it to work:
1. Build the FE and commit it (the change is in the FE):
   - go to the FE directory: `cd frontend`
   - build the FE: `npm run build-lib`
   - Commit the changes
2. Sign to commit to avoid the DCO error.

**Review by liranmauda — CHANGES_REQUESTED** [review]
Need to build the FE and commit the changes.

**Comment by rflorenc** [comment]
Got a whole lot of new stuff added after running those commands. Not sure if it is intended.
```
npm version
{
  noobaa_management_console: '0.4.0',
  npm: '7.20.6',
  node: '16.3.0',
  v8: '9.0.257.25-node.16',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '93',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1k',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0'
}
```

**Comment by nimrod-becker** [comment]
Prior to the final merge, please squash the commits. Sorry for not mentioning it before

**Comment by liranmauda** [comment]
> Got a whole lot of new stuff added after running those commands. Not sure if it is intended.
> 
> ```
> npm version
> {
>   noobaa_management_console: '0.4.0',
>   npm: '7.20.6',
>   node: '16.3.0',
>   v8: '9.0.257.25-node.16',
>   uv: '1.41.0',
>   zlib: '1.2.11',
>   brotli: '1.0.9',
>   ares: '1.17.1',
>   modules: '93',
>   nghttp2: '1.43.0',
>   napi: '8',
>   llhttp: '6.0.2',
>   openssl: '1.1.1k',
>   cldr: '39.0',
>   icu: '69.1',
>   tz: '2021a',
>   unicode: '13.0'
> }
> ```

Not desired.. 
It happened due to the fact that you have and use npm v7 which we still not using.
You can get a clear indication that it was npm v7 by looking at the package-lock.json and see this line: `"lockfileVersion": 2,`

Please drop this commit and redo, using npm v6 🙂

**Comment by rflorenc** [comment]
@liranmauda 

Pls have a look at the steps and confirm if all good.

https://gist.github.com/rflorenc/730abc1c727562f6dd4dadaf01229d50

By the time `npm run build-lib` finishes two lib.js files are deleted.
```
rlourenc:frontend$ git status
Auf Branch fix-issue-#6594
Ihr Branch ist auf demselben Stand wie 'origin/fix-issue-#6594'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add/rm <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git restore <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)
        gelöscht:       src/lib/lib.js
        gelöscht:       src/lib/lib.js.map

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
rlourenc:frontend$ ls -lrth src/lib/
total 8
-rw-r--r--  1 rlourenc  staff   1,7K  3 Jul 13:48 prism-tomorrow.css

```

**Comment by liranmauda** [comment]
Looks good.
now let's signed the commit + squash all into one.

**Comment by liranmauda** [comment]
@rflorenc 
I see that for some reason the "Bumping tar from 6.1.0 to 6.1.8" commit slipped in.
Please drop it. 
Eventually, we should see only the "fix typos" signed, commit and it should be synced to master. 
Then once the tests pass, I will be able to merge into master.

**Review by liranmauda — APPROVED** [review]

**Pull request merged**
