### PR TITLE
Replace revisions with current date

### PR DESCRIPTION
**Pull request by tangledbytes**
### Explain the changes
This PR replaces the fixed revision from `1` to current date.

### Testing Instructions:
1. Run `make rpm`
2. Check the generated RPM name, it should be of the format `noobaa-core-$(version)-$(date)`.

- [ ] Doc added/updated
- [ ] Tests added

### CODE REVIEW

**Comment by romayalon** [comment]
@tangledbytes should the actions be updated as well? 
https://github.com/noobaa/noobaa-core/blob/b95aebabaee642071dc21ff62396c61e031ddefa/.github/workflows/nightly-rpm-build.yml
https://github.com/noobaa/noobaa-core/blob/b95aebabaee642071dc21ff62396c61e031ddefa/.github/workflows/manual-build-rpm.yaml

**Comment by tangledbytes** [comment]
> @tangledbytes should the actions be updated as well? https://github.com/noobaa/noobaa-core/blob/b95aebabaee642071dc21ff62396c61e031ddefa/.github/workflows/nightly-rpm-build.yml https://github.com/noobaa/noobaa-core/blob/b95aebabaee642071dc21ff62396c61e031ddefa/.github/workflows/manual-build-rpm.yaml

@romayalon, I did not realize that we rename the artifacts in the workflow (I should have though). Fixing it here. Thank you.

**Review by liranmauda — APPROVED** [review]
LGTM, Just one question the RPM is marked as RHEL8, any reason?

**Comment by tangledbytes** [comment]
> LGTM, Just one question the RPM is marked as RHEL8, any reason?

No specific reason actually I guess 🤔

**Review by romayalon — APPROVED** [review]

**Pull request merged**
