### PR TITLE
CORS - support AWS APIs (NC and containerized)

### LINKED ISSUE #6080: Support S3 CORS API
**Is your feature request related to a problem? Please describe.**
When using aws s3 sdk to set cors rules, error occurred.
code:
```go
func setCors(bucketName string) error {
 region := "cn-northwest-1"
 if tools.Config.S3Region != "" {
  region = tools.Config.S3Region
 }
 sess := session.Must(session.NewSessionWithOptions(session.Options{
  SharedConfigState: session.SharedConfigEnable,
  Config: aws.Config{
   Region:   aws.String(region),
   Endpoint: aws.String(Key.EndPoint), //Bucket所在Endpoint
   HTTPClient: func() *http.Client {
    return &http.Client{
     Transport: func() *http.Transport {
      return &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}
     }(),
     Timeout: 3 * time.Second,
    }
   }(),
   //S3ForcePathStyle: aws.Bool(true),
  },
 }))
 svc := s3.New(sess)
 rule := s3.CORSRule{
  AllowedHeaders: aws.StringSlice([]string{"*"}),
  AllowedOrigins: aws.StringSlice([]string{"*"}),
  MaxAgeSeconds:  aws.Int64(3000),
  // Add HTTP methods CORS request that were specified in the CLI.
  AllowedMethods: aws.StringSlice([]string{"PUT", "POST", "GET"}),
 }
 params := s3.PutBucketCorsInput{
  Bucket: aws.String(bucketName),
  CORSConfiguration: &s3.CORSConfiguration{
   CORSRules: []*s3.CORSRule{&rule},
  },
 }
 _, err := svc.PutBucketCors(&params)
 if err != nil {
  log.Println("setCors, invoke s3 PutBucketCors error:", err)
  return err
 }
 log.Printf("setCors, Updated bucket %q CORS finished\n", bucketName)
 return nil
}
```
error message from noobaa:
> A header you provided implies functionality that is not implemented.
        status code: 501, request id: kc1muixr-as3c6z-12kx, host id: kc1muixr-as3c6z-12kx

**Describe the solution you'd like**
Support S3 CORS API, just like S3 BucketPolicy API support in v5.3 'Bomberman'.

**Describe alternatives you've considered**
Still thinking about it. If Noobaa developers know about any workarounds, please let me know.

**Additional context**
NA.

### PR DESCRIPTION
**Pull request by jackyalbo**
### Explain the changes
1. Adding support to the S3 CORS API: PUT/GET/DELETE
2. Changing default CORS behavior from a set of defaults to supporting the API following AWS documentation:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html
with some ideas from Azure documentation here:  https://learn.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services
3. Adding an option to create an anonymous bucket policy for read when getting a public-read acl, used by ceph-s3 tests

### Issues: Fixed #xxx / Gap #xxx
1. Fixed #6080 

### Testing Instructions:
1.  Added a few tests from ceph-tests suite.

- [ ] Doc added/updated
- [X] Tests added

### CODE REVIEW

**Comment by nimrod-becker** [comment]
I know it's still in draft, but remember to update the table from #8529 once @Neon-White merged it.
It could also be worth adding to bucketspace_s3 since it's a simple proxy in this case.

**Comment by jackyalbo** [comment]
> I know it's still in draft, but remember to update the table from #8529 once @Neon-White merged it. It could also be worth adding to bucketspace_s3 since it's a simple proxy in this case.

@nimrod-becker, about your second remark, it seems we don't support most of the bucket-level operations in bucketspace_s3 (lifecycle, tagging, encryption, bucket-policy, and so on), so I think we shouldn't add it also in this case, it can be added once we will support bucket-level operations in our APIs in the future (I remember that we wanted to work on it in the past)

**Comment by nimrod-becker** [comment]
We can, we can either do it all together or add this one,

**Review by liranmauda — APPROVED** [review]
LGTM

**Pull request merged**
