### PR TITLE
Invalidate cache on ListObjects

### PR DESCRIPTION
**Pull request by baum**
While listing objects compare hub and cache
and delete objects from cache if
- object is missing in hub (out of band delete)
- object is outdated (out of band object update)

Fixes:
- https://bugzilla.redhat.com/show_bug.cgi?id=2024107

Signed-off-by: Alexander Indenbaum <aindenba@redhat.com>

### CODE REVIEW

**Comment by guymguym** [comment]
Hey @baum I am not sure we should use the accidental list call to invalidate the cache - our design was to **validate** on GET object based on TTL.

See here -
https://github.com/noobaa/noobaa-core/blob/60c5ced7347593b8f488ed0dd1957a46ee40c08a/src/sdk/namespace_cache.js#L233-L237

Can you explain why our validations on GET did not work in your reproduction?

**Comment by baum** [comment]
Hello @guymguym,

Let me explain. The scenario is an out-of-band update of a cached object in the hub with a larger one. By design, NooBaa ListObjects() returns the hub's picture of the world.

The client (AWS CLI) is doing [sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html), and issues ranged [GetObject()](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html), after performing ListObjects(). The client uses an open range `X-`, the NooBaa endpoint  throws an InvalidRange exception [here](https://github.com/noobaa/noobaa-core/blob/60c5ced7347593b8f488ed0dd1957a46ee40c08a/src/util/http_utils.js#L218), since the range start `X` is greater than the cached object size.

The root cause is inconsistency between ListObjects() and GetObject(). Please see the [bz](https://bugzilla.redhat.com/show_bug.cgi?id=2024107) for more info.

**Comment by guymguym** [comment]
Hey, I saw the BZ and I believe I understand the issue.
My question is - why didn't our validation check catch it in get-object?
We check in every get object request to match the Etag/LastModifiedTime with the hub before we can use the locally cached object data.
In addition - we have a TTL setting which can be set to allow such inconsistency by design, in exchange for less validations.

**Comment by dannyzaken** [comment]
@guymguym AFAIK we don't validate on get-object unless the TTL has expired. 
I don't think we should treat it as an accidental list, it is a common pattern to list and then get-object. since the list returns the etag why isn't it a good idea to use it for validation?

**Comment by baum** [comment]
@dannyzaken 

Agree, let's use `etag` instead of `last_modified_time`. More robust this way.

```diff
diff --git a/src/sdk/namespace_cache.js b/src/sdk/namespace_cache.js
index 040a9f7e0..84d0919a1 100644
--- a/src/sdk/namespace_cache.js
+++ b/src/sdk/namespace_cache.js
@@ -211,7 +211,7 @@ class NamespaceCache {
                 const ho = hobjs[j]; // current hub list object
                 const missing_in_hub = (ho.key.localeCompare(co.key) > 0);
                 const same_key = (ho.key.localeCompare(co.key) === 0);
-                const outdated = (ho.last_modified_time > co.last_modified_time);
+                const outdated = (ho.etag !== co.etag);
                 should_delete = (missing_in_hub || (same_key && outdated));
                 if (same_key) {
                     j += 1; // next hub list object
```

**Pull request closed without merging**
