### PR TITLE
Get total mem and cpus from ENV if exists

### PR DESCRIPTION
**Pull request by nimrod-becker**
### Explain the changes
1. Get total MEM and CPUs from ENV if exists (pod requests)

### Issues: Fixed #xxx / Gap #xxx
1. 

### Testing Instructions:
1.

### CODE REVIEW

**Review by guymguym — APPROVED** [review]
How about adding this as a util functions to `os_utils`:
```
function get_memory() {
    return Number(process.env.CONTAINER_MEM_REQUEST) || os.totalmem();
}

function get_cpus() {
    return Number(process.env.CONTAINER_CPU_REQUEST) || os.cpus().length;
}
```

**Comment by nimrod-becker** [comment]
@guymguym thought about it, quite easy to do, didn't want to drag in os_utils (and its own deps) in places we don't already require it. Can change if you think its better

**Comment by guymguym** [comment]
The only problem is config.js which I agree is better left without requiring os_utils.
But for the rest I would do it.

**Review by guymguym — APPROVED** [review]
👍

**Review by jeniawhite — APPROVED** [review]

**Pull request merged**
